### ISSUE TITLE
Thrift 0.9.0 doesn't compile on OSX 10.9.2

### ISSUE THREAD

**Issue by densoh** [nkeyes/ok_hbase#18]
As a result this causes gem install ok_hbase to fail.  As a workaround I moved the thrift version up to 1.0.0 and it compiled, but I don't know if this will introduce any runtime side effects.

```
make "DESTDIR="
compiling binary_protocol_accelerated.c
compiling bytes.c
compiling compact_protocol.c
compiling memory_buffer.c
compiling protocol.c
compiling strlcpy.c
In file included from strlcpy.c:20:
./strlcpy.h:28:15: error: expected parameter declarator
extern size_t strlcpy(char *, const char *, size_t);
              ^
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:62: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                                                             ^
/usr/include/secure/_common.h:30:32: note: expanded from macro '_USE_FORTIFY_LEVEL'
#    define _USE_FORTIFY_LEVEL 2
                               ^
In file included from strlcpy.c:20:
./strlcpy.h:28:15: error: expected ')'
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:62: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                                                             ^
/usr/include/secure/_common.h:30:32: note: expanded from macro '_USE_FORTIFY_LEVEL'
#    define _USE_FORTIFY_LEVEL 2
                               ^
./strlcpy.h:28:15: note: to match this '('
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:53: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                                                    ^
In file included from strlcpy.c:20:
./strlcpy.h:28:15: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
extern size_t strlcpy(char *, const char *, size_t);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^~~~~~~~~~~~~~~~~~~~
/usr/include/secure/_common.h:39:31: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                              ^~~~~~~~~~~~~~~~~~~~~
In file included from strlcpy.c:20:
./strlcpy.h:28:15: error: conflicting types for '__builtin___strlcpy_chk'
/usr/include/secure/_string.h:105:3: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
  ^
./strlcpy.h:28:15: note: '__builtin___strlcpy_chk' is a builtin with type 'unsigned long (char *, const char *, unsigned long, unsigned long)'
/usr/include/secure/_string.h:105:3: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
  ^
4 errors generated.
make: *** [strlcpy.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/dennissoh/.rvm/gems/ruby-2.0.0-p247/gems/thrift-0.9.0 for inspection.
Results logged to /Users/dennissoh/.rvm/gems/ruby-2.0.0-p247/extensions/x86_64-darwin-13/2.0.0/thrift-0.9.0/gem_make.out
An error occurred while installing thrift (0.9.0), and Bundler cannot continue.
Make sure that `gem install thrift -v '0.9.0'` succeeds before bundling.
```

**Comment by Geesu** [comment]
http://www.extendi.it/blog/2013/12/17/7-thrift-gem-0-9-1-fails-to-build-on-os-x-mavericks-and-ruby-1-9-3

**Comment by densoh** [comment]
Hi: I updated the version of thrift on my fork and it resolved the
compilation error without needing any compiler flags.  I put in a pull
request for that change, feel free to accept (or reject) it.

Thanks!

**Comment by nkeyes** [comment]
Hey, sorry for the neglect guys, I haven't used this in over a year.
@densoh I'll merge this after I see the tests pass.

**Comment by nkeyes** [comment]
@densoh the latest stable version of thrift is 0.9.1, so I won't merge this.
Have you tried 0.9.1? (your initial title says 0.9.0)

**Comment by nkeyes** [comment]
@denosh FYI: I was able to install thrift 0.9.1 on OS X Mavericks (10.9.4)

``` zsh
➜  ok_hbase git:(master) ✗ gem install thrift
Fetching: thrift-0.9.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed thrift-0.9.1
Enclosing class/module 'thrift_module' for class BinaryProtocolAccelerated not known
Installing ri documentation for thrift-0.9.1
1 gem installed
➜  ok_hbase git:(master) ✗
```
